export default {
  'copy-formula': '复制AI对话中公式',
  'deepseek-to-image': 'DeepSeek导出图片',
  'deepseek-to-word': 'DeepSeek导出Word',
  'chatgpt-to-word': 'ChatGPT导出Word',
  'gemini-to-word': 'Gemini导出Word',
  'kimi-to-word': 'Kimi导出Word',
  'doubao-to-word': '豆包导出Word',
  'qwen-to-word': '千问导出Word',
  'yuanbao-to-word': '元宝导出Word',
  'gemini-to-md': 'Gemini导出Markdown',
  'gemini-canvas-to-word': 'Gemini Canvas导出Word',
  'gemini-canvas-to-md': 'Gemini Canvas导出Markdown',
  'gemini-deep-research-to-word': 'Gemini Deep Research导出Word',
  'gemini-deep-research-to-md': 'Gemini Deep Research导出Markdown',
  'aistudio-to-word': 'Google AI Studio导出Word',
  'doubao-side-to-word': '豆包“帮我写作”导出Word',
  'select-word-template': '选择Word模版',
  'remove-dividers': '去除Word的分割线',
  'remove-emoji': '去除Word的Emoji表情',
  'mcp-server': 'Markdown转Word MCP',
  'claude-skill': 'Claude Code Skill'
}
